/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CostCalculatorRouteImport } from './routes/cost-calculator'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ApiPublicIngestPointerRouteImport } from './routes/api/public/ingest-pointer'
import { Route as ApiPublicIngestReplayRouteImport } from './routes/api/public/ingest-replay'
import { Route as ApiPublicLogSignalRouteImport } from './routes/api/public/log-signal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CostCalculatorRoute = CostCalculatorRouteImport.update({
  id: '/cost-calculator',
  path: '/cost-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestPointerRoute = ApiPublicIngestPointerRouteImport.update({
  id: '/api/public/ingest-pointer',
  path: '/api/public/ingest-pointer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestReplayRoute = ApiPublicIngestReplayRouteImport.update({
  id: '/api/public/ingest-replay',
  path: '/api/public/ingest-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogSignalRoute = ApiPublicLogSignalRouteImport.update({
  id: '/api/public/log-signal',
  path: '/api/public/log-signal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cost-calculator': typeof CostCalculatorRoute
  '/priorities': typeof PrioritiesRoute
  '/volunteer': typeof VolunteerRoute
  '/api/public/ingest-pointer': typeof ApiPublicIngestPointerRoute
  '/api/public/ingest-replay': typeof ApiPublicIngestReplayRoute
  '/api/public/log-signal': typeof ApiPublicLogSignalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cost-calculator': typeof CostCalculatorRoute
  '/priorities': typeof PrioritiesRoute
  '/volunteer': typeof VolunteerRoute
  '/api/public/ingest-pointer': typeof ApiPublicIngestPointerRoute
  '/api/public/ingest-replay': typeof ApiPublicIngestReplayRoute
  '/api/public/log-signal': typeof ApiPublicLogSignalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cost-calculator': typeof CostCalculatorRoute
  '/priorities': typeof PrioritiesRoute
  '/volunteer': typeof VolunteerRoute
  '/api/public/ingest-pointer': typeof ApiPublicIngestPointerRoute
  '/api/public/ingest-replay': typeof ApiPublicIngestReplayRoute
  '/api/public/log-signal': typeof ApiPublicLogSignalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cost-calculator'
    | '/priorities'
    | '/volunteer'
    | '/api/public/ingest-pointer'
    | '/api/public/ingest-replay'
    | '/api/public/log-signal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cost-calculator'
    | '/priorities'
    | '/volunteer'
    | '/api/public/ingest-pointer'
    | '/api/public/ingest-replay'
    | '/api/public/log-signal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cost-calculator'
    | '/priorities'
    | '/volunteer'
    | '/api/public/ingest-pointer'
    | '/api/public/ingest-replay'
    | '/api/public/log-signal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CostCalculatorRoute: typeof CostCalculatorRoute
  PrioritiesRoute: typeof PrioritiesRoute
  VolunteerRoute: typeof VolunteerRoute
  ApiPublicIngestPointerRoute: typeof ApiPublicIngestPointerRoute
  ApiPublicIngestReplayRoute: typeof ApiPublicIngestReplayRoute
  ApiPublicLogSignalRoute: typeof ApiPublicLogSignalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-calculator': {
      id: '/cost-calculator'
      path: '/cost-calculator'
      fullPath: '/cost-calculator'
      preLoaderRoute: typeof CostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-pointer': {
      id: '/api/public/ingest-pointer'
      path: '/api/public/ingest-pointer'
      fullPath: '/api/public/ingest-pointer'
      preLoaderRoute: typeof ApiPublicIngestPointerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-replay': {
      id: '/api/public/ingest-replay'
      path: '/api/public/ingest-replay'
      fullPath: '/api/public/ingest-replay'
      preLoaderRoute: typeof ApiPublicIngestReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-signal': {
      id: '/api/public/log-signal'
      path: '/api/public/log-signal'
      fullPath: '/api/public/log-signal'
      preLoaderRoute: typeof ApiPublicLogSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CostCalculatorRoute: CostCalculatorRoute,
  PrioritiesRoute: PrioritiesRoute,
  VolunteerRoute: VolunteerRoute,
  ApiPublicIngestPointerRoute: ApiPublicIngestPointerRoute,
  ApiPublicIngestReplayRoute: ApiPublicIngestReplayRoute,
  ApiPublicLogSignalRoute: ApiPublicLogSignalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
