/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCanvassRouteImport } from './routes/admin/canvass'
import { Route as AdminDraftsRouteImport } from './routes/admin/drafts'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as AdminHeatmapsRouteImport } from './routes/admin/heatmaps'
import { Route as AdminIntentRouteImport } from './routes/admin/intent'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminVoterMapRouteImport } from './routes/admin/voter-map'
import { Route as AdminVotersRouteImport } from './routes/admin/voters'
import { Route as CanvassIndexRouteImport } from './routes/canvass.index'
import { Route as CanvassGuideRouteImport } from './routes/canvass.guide'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewUnlockRouteImport } from './routes/review.unlock'
import { Route as ApiPublicCanvassSyncRouteImport } from './routes/api/public/canvass-sync'
import { Route as ApiPublicIngestPointerRouteImport } from './routes/api/public/ingest-pointer'
import { Route as ApiPublicIngestReplayRouteImport } from './routes/api/public/ingest-replay'
import { Route as ApiPublicLogSignalRouteImport } from './routes/api/public/log-signal'
import { Route as CanvassWalkTurfIdRouteImport } from './routes/canvass.walk.$turfId'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCanvassRoute = AdminCanvassRouteImport.update({
  id: '/admin/canvass',
  path: '/admin/canvass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDraftsRoute = AdminDraftsRouteImport.update({
  id: '/admin/drafts',
  path: '/admin/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeatmapsRoute = AdminHeatmapsRouteImport.update({
  id: '/admin/heatmaps',
  path: '/admin/heatmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntentRoute = AdminIntentRouteImport.update({
  id: '/admin/intent',
  path: '/admin/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoterMapRoute = AdminVoterMapRouteImport.update({
  id: '/admin/voter-map',
  path: '/admin/voter-map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotersRoute = AdminVotersRouteImport.update({
  id: '/admin/voters',
  path: '/admin/voters',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvassIndexRoute = CanvassIndexRouteImport.update({
  id: '/canvass/',
  path: '/canvass/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvassGuideRoute = CanvassGuideRouteImport.update({
  id: '/canvass/guide',
  path: '/canvass/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewUnlockRoute = ReviewUnlockRouteImport.update({
  id: '/review/unlock',
  path: '/review/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCanvassSyncRoute = ApiPublicCanvassSyncRouteImport.update({
  id: '/api/public/canvass-sync',
  path: '/api/public/canvass-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestPointerRoute = ApiPublicIngestPointerRouteImport.update({
  id: '/api/public/ingest-pointer',
  path: '/api/public/ingest-pointer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestReplayRoute = ApiPublicIngestReplayRouteImport.update({
  id: '/api/public/ingest-replay',
  path: '/api/public/ingest-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogSignalRoute = ApiPublicLogSignalRouteImport.update({
  id: '/api/public/log-signal',
  path: '/api/public/log-signal',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvassWalkTurfIdRoute = CanvassWalkTurfIdRouteImport.update({
  id: '/canvass/walk/$turfId',
  path: '/canvass/walk/$turfId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pilot': typeof PilotRoute
  '/priorities': typeof PrioritiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/canvass': typeof AdminCanvassRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/heatmaps': typeof AdminHeatmapsRoute
  '/admin/intent': typeof AdminIntentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/voter-map': typeof AdminVoterMapRoute
  '/admin/voters': typeof AdminVotersRoute
  '/canvass/guide': typeof CanvassGuideRoute
  '/review/unlock': typeof ReviewUnlockRoute
  '/admin/': typeof AdminIndexRoute
  '/canvass/': typeof CanvassIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/api/public/canvass-sync': typeof ApiPublicCanvassSyncRoute
  '/api/public/ingest-pointer': typeof ApiPublicIngestPointerRoute
  '/api/public/ingest-replay': typeof ApiPublicIngestReplayRoute
  '/api/public/log-signal': typeof ApiPublicLogSignalRoute
  '/canvass/walk/$turfId': typeof CanvassWalkTurfIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pilot': typeof PilotRoute
  '/priorities': typeof PrioritiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/canvass': typeof AdminCanvassRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/heatmaps': typeof AdminHeatmapsRoute
  '/admin/intent': typeof AdminIntentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/voter-map': typeof AdminVoterMapRoute
  '/admin/voters': typeof AdminVotersRoute
  '/canvass/guide': typeof CanvassGuideRoute
  '/review/unlock': typeof ReviewUnlockRoute
  '/admin': typeof AdminIndexRoute
  '/canvass': typeof CanvassIndexRoute
  '/review': typeof ReviewIndexRoute
  '/api/public/canvass-sync': typeof ApiPublicCanvassSyncRoute
  '/api/public/ingest-pointer': typeof ApiPublicIngestPointerRoute
  '/api/public/ingest-replay': typeof ApiPublicIngestReplayRoute
  '/api/public/log-signal': typeof ApiPublicLogSignalRoute
  '/canvass/walk/$turfId': typeof CanvassWalkTurfIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pilot': typeof PilotRoute
  '/priorities': typeof PrioritiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/canvass': typeof AdminCanvassRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/heatmaps': typeof AdminHeatmapsRoute
  '/admin/intent': typeof AdminIntentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/voter-map': typeof AdminVoterMapRoute
  '/admin/voters': typeof AdminVotersRoute
  '/canvass/guide': typeof CanvassGuideRoute
  '/review/unlock': typeof ReviewUnlockRoute
  '/admin/': typeof AdminIndexRoute
  '/canvass/': typeof CanvassIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/api/public/canvass-sync': typeof ApiPublicCanvassSyncRoute
  '/api/public/ingest-pointer': typeof ApiPublicIngestPointerRoute
  '/api/public/ingest-replay': typeof ApiPublicIngestReplayRoute
  '/api/public/log-signal': typeof ApiPublicLogSignalRoute
  '/canvass/walk/$turfId': typeof CanvassWalkTurfIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pilot'
    | '/priorities'
    | '/reset-password'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/canvass'
    | '/admin/drafts'
    | '/admin/export'
    | '/admin/heatmaps'
    | '/admin/intent'
    | '/admin/login'
    | '/admin/voter-map'
    | '/admin/voters'
    | '/canvass/guide'
    | '/review/unlock'
    | '/admin/'
    | '/canvass/'
    | '/review/'
    | '/api/public/canvass-sync'
    | '/api/public/ingest-pointer'
    | '/api/public/ingest-replay'
    | '/api/public/log-signal'
    | '/canvass/walk/$turfId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pilot'
    | '/priorities'
    | '/reset-password'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/canvass'
    | '/admin/drafts'
    | '/admin/export'
    | '/admin/heatmaps'
    | '/admin/intent'
    | '/admin/login'
    | '/admin/voter-map'
    | '/admin/voters'
    | '/canvass/guide'
    | '/review/unlock'
    | '/admin'
    | '/canvass'
    | '/review'
    | '/api/public/canvass-sync'
    | '/api/public/ingest-pointer'
    | '/api/public/ingest-replay'
    | '/api/public/log-signal'
    | '/canvass/walk/$turfId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pilot'
    | '/priorities'
    | '/reset-password'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/canvass'
    | '/admin/drafts'
    | '/admin/export'
    | '/admin/heatmaps'
    | '/admin/intent'
    | '/admin/login'
    | '/admin/voter-map'
    | '/admin/voters'
    | '/canvass/guide'
    | '/review/unlock'
    | '/admin/'
    | '/canvass/'
    | '/review/'
    | '/api/public/canvass-sync'
    | '/api/public/ingest-pointer'
    | '/api/public/ingest-replay'
    | '/api/public/log-signal'
    | '/canvass/walk/$turfId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PilotRoute: typeof PilotRoute
  PrioritiesRoute: typeof PrioritiesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VolunteerRoute: typeof VolunteerRoute
  AdminCanvassRoute: typeof AdminCanvassRoute
  AdminDraftsRoute: typeof AdminDraftsRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminHeatmapsRoute: typeof AdminHeatmapsRoute
  AdminIntentRoute: typeof AdminIntentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminVoterMapRoute: typeof AdminVoterMapRoute
  AdminVotersRoute: typeof AdminVotersRoute
  CanvassGuideRoute: typeof CanvassGuideRoute
  ReviewUnlockRoute: typeof ReviewUnlockRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CanvassIndexRoute: typeof CanvassIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ApiPublicCanvassSyncRoute: typeof ApiPublicCanvassSyncRoute
  ApiPublicIngestPointerRoute: typeof ApiPublicIngestPointerRoute
  ApiPublicIngestReplayRoute: typeof ApiPublicIngestReplayRoute
  ApiPublicLogSignalRoute: typeof ApiPublicLogSignalRoute
  CanvassWalkTurfIdRoute: typeof CanvassWalkTurfIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/canvass': {
      id: '/admin/canvass'
      path: '/admin/canvass'
      fullPath: '/admin/canvass'
      preLoaderRoute: typeof AdminCanvassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drafts': {
      id: '/admin/drafts'
      path: '/admin/drafts'
      fullPath: '/admin/drafts'
      preLoaderRoute: typeof AdminDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/heatmaps': {
      id: '/admin/heatmaps'
      path: '/admin/heatmaps'
      fullPath: '/admin/heatmaps'
      preLoaderRoute: typeof AdminHeatmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/intent': {
      id: '/admin/intent'
      path: '/admin/intent'
      fullPath: '/admin/intent'
      preLoaderRoute: typeof AdminIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voter-map': {
      id: '/admin/voter-map'
      path: '/admin/voter-map'
      fullPath: '/admin/voter-map'
      preLoaderRoute: typeof AdminVoterMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voters': {
      id: '/admin/voters'
      path: '/admin/voters'
      fullPath: '/admin/voters'
      preLoaderRoute: typeof AdminVotersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvass/': {
      id: '/canvass/'
      path: '/canvass'
      fullPath: '/canvass/'
      preLoaderRoute: typeof CanvassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvass/guide': {
      id: '/canvass/guide'
      path: '/canvass/guide'
      fullPath: '/canvass/guide'
      preLoaderRoute: typeof CanvassGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/unlock': {
      id: '/review/unlock'
      path: '/review/unlock'
      fullPath: '/review/unlock'
      preLoaderRoute: typeof ReviewUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/canvass-sync': {
      id: '/api/public/canvass-sync'
      path: '/api/public/canvass-sync'
      fullPath: '/api/public/canvass-sync'
      preLoaderRoute: typeof ApiPublicCanvassSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-pointer': {
      id: '/api/public/ingest-pointer'
      path: '/api/public/ingest-pointer'
      fullPath: '/api/public/ingest-pointer'
      preLoaderRoute: typeof ApiPublicIngestPointerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-replay': {
      id: '/api/public/ingest-replay'
      path: '/api/public/ingest-replay'
      fullPath: '/api/public/ingest-replay'
      preLoaderRoute: typeof ApiPublicIngestReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-signal': {
      id: '/api/public/log-signal'
      path: '/api/public/log-signal'
      fullPath: '/api/public/log-signal'
      preLoaderRoute: typeof ApiPublicLogSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvass/walk/$turfId': {
      id: '/canvass/walk/$turfId'
      path: '/canvass/walk/$turfId'
      fullPath: '/canvass/walk/$turfId'
      preLoaderRoute: typeof CanvassWalkTurfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PilotRoute: PilotRoute,
  PrioritiesRoute: PrioritiesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VolunteerRoute: VolunteerRoute,
  AdminCanvassRoute: AdminCanvassRoute,
  AdminDraftsRoute: AdminDraftsRoute,
  AdminExportRoute: AdminExportRoute,
  AdminHeatmapsRoute: AdminHeatmapsRoute,
  AdminIntentRoute: AdminIntentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminVoterMapRoute: AdminVoterMapRoute,
  AdminVotersRoute: AdminVotersRoute,
  CanvassGuideRoute: CanvassGuideRoute,
  ReviewUnlockRoute: ReviewUnlockRoute,
  AdminIndexRoute: AdminIndexRoute,
  CanvassIndexRoute: CanvassIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ApiPublicCanvassSyncRoute: ApiPublicCanvassSyncRoute,
  ApiPublicIngestPointerRoute: ApiPublicIngestPointerRoute,
  ApiPublicIngestReplayRoute: ApiPublicIngestReplayRoute,
  ApiPublicLogSignalRoute: ApiPublicLogSignalRoute,
  CanvassWalkTurfIdRoute: CanvassWalkTurfIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
